#!/usr/bin/env python3
"""Branding-profile loader for site/build.py.

Reads config/branding.yaml — the single customization point for the
published site's identity, theme, chart palettes, feeds, and analytics —
validates it against the schema below, and exposes helpers that
site/build.py consumes. Stdlib-only, like everything under site/.

Design contract (see docs/customization.md):
  - DEFAULTS below mirrors config/branding.yaml as shipped upstream. A
    missing config file, or any missing key, falls back to the identical
    value — so a fork that deletes half the file still builds the
    upstream-branded site.
  - Unknown keys FAIL the build (fail-loud beats a silently ignored typo).
  - Theme values are an override layer: empty string → styles.css keeps
    owning the value; non-empty → render_branding_css() emits a CSS
    custom-property override block loaded after styles.css.

The YAML-subset parser is shared with tools/compose_prompts.py (same
syntax rules as config/org-profile.yaml; loaded by file path so it works
under both `python3 site/build.py` and the test-suite import).
"""

from __future__ import annotations

import copy
import importlib.util
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
BRANDING_PATH = ROOT / "config" / "branding.yaml"
BRANDING_ASSETS_DIR = Path(__file__).resolve().parent / "branding"


class BrandingError(Exception):
    """Anything wrong with config/branding.yaml. Aborts the build."""


def _yaml_parser():
    """Load parse_yaml_subset from tools/compose_prompts.py by path."""
    src = ROOT / "tools" / "compose_prompts.py"
    if not src.exists():
        raise BrandingError(
            f"cannot parse config/branding.yaml: {src} is missing "
            "(it provides the shared YAML-subset parser)"
        )
    spec = importlib.util.spec_from_file_location("_ctipilot_compose_prompts", src)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.parse_yaml_subset, mod.ProfileError


# --- Schema + upstream defaults (mirror of config/branding.yaml) -----------

_THEME_COLOR_KEYS = (
    "bg", "bg_elev", "bg_elev_2", "border", "border_soft",
    "text", "text_soft", "text_muted", "link", "link_hover",
    "accent", "accent_soft", "accent_fg", "warn", "crit", "ok", "info",
    "kbd_bg", "selection", "topbar_bg", "shadow",
)

DEFAULTS: dict[str, Any] = {
    "branding_version": "1",
    "site": {
        "name": "ctipilot.ch",
        "wordmark_strong": "ctipilot",
        "wordmark_accent": ".ch",
        "tagline": "Switzerland, Europe & Public Sector",
        "lede": (
            "Continuous cyber threat intelligence — Switzerland, Europe, "
            "and the public sector. Published the hour it is verified; "
            "source-linked, IOC-free, autonomously generated by an LLM."
        ),
        "meta_description": (
            "Continuous cyber threat intelligence (CTI) pipeline covering "
            "Switzerland, Europe, and the public sector — per-finding "
            "entries, a time-window brief, source-linked, IOC-free, "
            "autonomously generated by an LLM."
        ),
        "footer_tagline": "Switzerland · Europe · Public sector",
        "footer_lede": (
            "Continuous cyber threat intelligence for Tier 2/3 SOC, IR\n"
            "and detection engineers. Source-linked, IOC-free, autonomously\n"
            "generated by an LLM with parallel research and verification."
        ),
        "copyright_note": "published under the MIT License.\nMade in Switzerland.",
        "url": "https://ctipilot.ch/",
        "github_repo": "OwlsNightCatch/ctipilot",
        "lang": "en",
        "locale": "en_US",
    },
    "logo": {
        "header_mark": "",
        "footer_mark": "",
        "footer_mark_text": "CTI",
        "favicon": "",
        "favicon_text": "CTI",
        "favicon_bg": "#e85d75",
        "favicon_fg": "#0e1116",
    },
    "theme": {
        "fonts": {"sans": "", "serif": "", "mono": ""},
        "tokens": {"radius": "", "radius_lg": "", "topbar_h": ""},
        "dark": {k: "" for k in _THEME_COLOR_KEYS},
        "light": {k: "" for k in _THEME_COLOR_KEYS},
    },
    "charts": {
        "accent_rgb": "",
        "info_rgb": "",
        "model_palette": [],
        "entity_palette": [],
        "reliability_high": "",
        "reliability_medium": "",
        "reliability_low": "",
    },
    "analytics": {
        "provider": "umami",
        "umami": {
            "website_id": "abe09860-85be-4b06-8383-002f2e598061",
            "script_host": "https://cloud.umami.is",
            "beacon_host": "https://gateway.umami.is",
        },
    },
    "feeds": {
        "daily_description": (
            "Day-by-day cyber threat intelligence coverage of Switzerland, "
            "Europe, and the public sector — autonomously generated, "
            "source-linked, IOC-free."
        ),
        "weekly_description": (
            "Weekly cyber threat intelligence summaries — multi-day "
            "campaigns, sector patterns, policy horizon."
        ),
        "items_description": (
            "Individual intelligence entries as they are verified and "
            "published (threats, incidents, vulnerabilities, research, "
            "updates, deep dives) — pubDate is the discovery moment."
        ),
        "sector_slices": [],
    },
    "trends": {
        "cohorts": [],
    },
}

# Keys whose value is a list (of strings or of mappings) — everything else
# in the schema is a string or a nested mapping.
_LIST_KEYS = {
    ("charts", "model_palette"),
    ("charts", "entity_palette"),
    ("feeds", "sector_slices"),
    ("trends", "cohorts"),
}

_SECTOR_SLICE_KEYS = {"filename", "title_suffix", "description", "sectors", "tags"}
_COHORT_KEYS = {"key", "title", "match", "tags", "sectors", "regions"}


# --- Merge + validation -----------------------------------------------------

def _merge(user: Any, default: Any, path: str) -> Any:
    """Overlay the user's config on DEFAULTS, failing loud on unknown keys
    and shape mismatches. Lists replace wholesale; strings replace; dicts
    merge key-by-key."""
    if isinstance(default, dict):
        if not isinstance(user, dict):
            raise BrandingError(
                f"config/branding.yaml: {path or '<top>'} must be a mapping, "
                f"got {type(user).__name__}"
            )
        merged = {}
        for key in user:
            if key not in default:
                raise BrandingError(
                    f"config/branding.yaml: unknown key {path + key!r} "
                    f"(known: {', '.join(sorted(default))})"
                )
        for key, dval in default.items():
            if key in user:
                merged[key] = _merge(user[key], dval, f"{path}{key}.")
            else:
                merged[key] = copy.deepcopy(dval)
        return merged
    if isinstance(default, list):
        if not isinstance(user, list):
            raise BrandingError(
                f"config/branding.yaml: {path.rstrip('.')} must be a list, "
                f"got {type(user).__name__}"
            )
        return copy.deepcopy(user)
    # Scalar (string) leaf.
    if not isinstance(user, str):
        raise BrandingError(
            f"config/branding.yaml: {path.rstrip('.')} must be a string, "
            f"got {type(user).__name__}"
        )
    return user


def _req_slice_str(entry: dict[str, Any], key: str, ctx: str) -> str:
    v = entry.get(key)
    if not isinstance(v, str) or not v.strip():
        raise BrandingError(f"config/branding.yaml: {ctx} needs a non-empty {key!r}")
    return v.strip()


def _str_list(entry: dict[str, Any], key: str, ctx: str) -> tuple[str, ...]:
    v = entry.get(key, [])
    if isinstance(v, str):
        v = [v] if v else []
    if not isinstance(v, list) or not all(isinstance(x, str) for x in v):
        raise BrandingError(f"config/branding.yaml: {ctx} {key!r} must be a list of strings")
    return tuple(x.strip() for x in v if x.strip())


def _validate(b: dict[str, Any]) -> None:
    provider = b["analytics"]["provider"]
    if provider not in ("umami", "none"):
        raise BrandingError(
            f"config/branding.yaml: analytics.provider must be 'umami' or "
            f"'none', got {provider!r}"
        )
    if provider == "umami":
        um = b["analytics"]["umami"]
        for k in ("website_id", "script_host", "beacon_host"):
            if not um[k].strip():
                raise BrandingError(
                    f"config/branding.yaml: analytics.umami.{k} must be set "
                    "when analytics.provider is 'umami' (or set provider: \"none\")"
                )
        for k in ("script_host", "beacon_host"):
            if not um[k].startswith("https://"):
                raise BrandingError(
                    f"config/branding.yaml: analytics.umami.{k} must be an https:// origin"
                )
    for k in ("name", "wordmark_strong", "url", "github_repo", "lang", "locale"):
        if not b["site"][k].strip():
            raise BrandingError(f"config/branding.yaml: site.{k} must not be empty")
    if not b["site"]["url"].startswith(("https://", "http://")):
        raise BrandingError("config/branding.yaml: site.url must be an http(s) URL")
    # Referenced logo/favicon files must exist under site/branding/.
    for k in ("header_mark", "footer_mark", "favicon"):
        rel = b["logo"][k].strip()
        if not rel:
            continue
        if rel.startswith("/") or ".." in rel.split("/"):
            raise BrandingError(
                f"config/branding.yaml: logo.{k} must be a plain relative "
                f"path under site/branding/, got {rel!r}"
            )
        if not (BRANDING_ASSETS_DIR / rel).is_file():
            raise BrandingError(
                f"config/branding.yaml: logo.{k} points at "
                f"site/branding/{rel} which does not exist"
            )
    for pal in ("model_palette", "entity_palette"):
        vals = b["charts"][pal]
        if not all(isinstance(x, str) and x.strip() for x in vals):
            raise BrandingError(
                f"config/branding.yaml: charts.{pal} must be a list of CSS colors"
            )
    for rgb_key in ("accent_rgb", "info_rgb"):
        v = b["charts"][rgb_key].strip()
        if v and len([p for p in v.split(",") if p.strip().isdigit()]) != 3:
            raise BrandingError(
                f"config/branding.yaml: charts.{rgb_key} must look like "
                f"\"R,G,B\" (three integers), got {v!r}"
            )
    seen_files: set[str] = set()
    for i, entry in enumerate(b["feeds"]["sector_slices"]):
        ctx = f"feeds.sector_slices[{i}]"
        if not isinstance(entry, dict):
            raise BrandingError(f"config/branding.yaml: {ctx} must be a mapping")
        unknown = set(entry) - _SECTOR_SLICE_KEYS
        if unknown:
            raise BrandingError(
                f"config/branding.yaml: {ctx} has unknown key(s) {sorted(unknown)}"
            )
        fname = _req_slice_str(entry, "filename", ctx)
        if not fname.startswith("feed-") or not fname.endswith(".xml") or "/" in fname:
            raise BrandingError(
                f"config/branding.yaml: {ctx} filename must match feed-*.xml, got {fname!r}"
            )
        if fname in seen_files:
            raise BrandingError(f"config/branding.yaml: duplicate sector-slice filename {fname!r}")
        seen_files.add(fname)
        _req_slice_str(entry, "title_suffix", ctx)
        _req_slice_str(entry, "description", ctx)
        if not _str_list(entry, "sectors", ctx) and not _str_list(entry, "tags", ctx):
            raise BrandingError(
                f"config/branding.yaml: {ctx} needs at least one sector or tag"
            )
    seen_keys: set[str] = set()
    for i, entry in enumerate(b["trends"]["cohorts"]):
        ctx = f"trends.cohorts[{i}]"
        if not isinstance(entry, dict):
            raise BrandingError(f"config/branding.yaml: {ctx} must be a mapping")
        unknown = set(entry) - _COHORT_KEYS
        if unknown:
            raise BrandingError(
                f"config/branding.yaml: {ctx} has unknown key(s) {sorted(unknown)}"
            )
        key = _req_slice_str(entry, "key", ctx)
        if key in seen_keys:
            raise BrandingError(f"config/branding.yaml: duplicate cohort key {key!r}")
        seen_keys.add(key)
        _req_slice_str(entry, "title", ctx)
        match = entry.get("match", "any") or "any"
        if match not in ("any", "all"):
            raise BrandingError(
                f"config/branding.yaml: {ctx} match must be 'any' or 'all', got {match!r}"
            )
        if not (_str_list(entry, "tags", ctx) or _str_list(entry, "sectors", ctx)
                or _str_list(entry, "regions", ctx)):
            raise BrandingError(
                f"config/branding.yaml: {ctx} needs at least one tag, sector, or region"
            )


def load_branding(path: Path = BRANDING_PATH) -> dict[str, Any]:
    """Parse + merge + validate config/branding.yaml. Missing file →
    upstream DEFAULTS (a fork may delete the file entirely)."""
    if not path.exists():
        return copy.deepcopy(DEFAULTS)
    parse_yaml_subset, profile_error = _yaml_parser()
    try:
        raw = parse_yaml_subset(path.read_text(encoding="utf-8"), source=str(path))
    except profile_error as e:
        raise BrandingError(str(e)) from e
    merged = _merge(raw, DEFAULTS, "")
    _validate(merged)
    return merged


# --- Derived artifacts -------------------------------------------------------

def _css_decls(section: dict[str, str], keys: tuple[str, ...]) -> list[str]:
    return [
        f"  --{k.replace('_', '-')}: {section[k].strip()};"
        for k in keys
        if section.get(k, "").strip()
    ]


def render_branding_css(branding: dict[str, Any]) -> str:
    """CSS custom-property override block for every non-empty theme value.
    Empty string when nothing is overridden (the upstream-default state) —
    the build then emits no branding.css and no <link> for it.

    Loaded AFTER styles.css, so plain `:root` declarations win the cascade
    for dark/global tokens; light-theme overrides mirror styles.css's two
    selector shapes (`@media prefers-color-scheme` + explicit
    `[data-theme="light"]`) so they win those by source order too."""
    theme = branding["theme"]
    root_lines = (
        _css_decls(theme["fonts"], ("sans", "serif", "mono"))
        + _css_decls(theme["tokens"], ("radius", "radius_lg", "topbar_h"))
        + _css_decls(theme["dark"], _THEME_COLOR_KEYS)
    )
    light_lines = _css_decls(theme["light"], _THEME_COLOR_KEYS)
    if not root_lines and not light_lines:
        return ""
    parts: list[str] = [
        "/* GENERATED from config/branding.yaml (theme section) — do not edit.",
        "   Loaded after styles.css; every declaration here intentionally",
        "   overrides the upstream design default. */",
    ]
    if root_lines:
        parts.append(":root {\n" + "\n".join(root_lines) + "\n}")
    if light_lines:
        indented = "\n".join("  " + ln for ln in light_lines)
        parts.append(
            "@media (prefers-color-scheme: light) {\n"
            '  :root:not([data-theme="dark"]) {\n' + indented + "\n  }\n}"
        )
        parts.append(':root[data-theme="light"] {\n' + "\n".join(light_lines) + "\n}")
    return "\n".join(parts) + "\n"


def _uri_color(color: str) -> str:
    return color.replace("#", "%23")


def default_favicon_href(branding: dict[str, Any]) -> str:
    """Generated SVG favicon as a data: URI — rounded square, monospace
    text — from logo.favicon_{bg,fg,text}. Only used when logo.favicon
    names no file."""
    logo = branding["logo"]
    text = "".join(
        ch if ch.isalnum() else "" for ch in logo["favicon_text"].strip()
    )[:4] or "CTI"
    return (
        "data:image/svg+xml,"
        "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E"
        f"%3Crect width='32' height='32' rx='6' fill='{_uri_color(logo['favicon_bg'].strip())}'/%3E"
        "%3Ctext x='50%25' y='52%25' text-anchor='middle' dominant-baseline='middle' "
        "font-family='ui-monospace,monospace' font-size='15' font-weight='700' "
        f"fill='{_uri_color(logo['favicon_fg'].strip())}'%3E{text}%3C/text%3E%3C/svg%3E"
    )


def sector_feed_slices(
    branding: dict[str, Any],
    default: list[tuple[str, tuple[str, ...], tuple[str, ...], str, str]],
) -> list[tuple[str, tuple[str, ...], tuple[str, ...], str, str]]:
    """feeds.sector_slices in build.py's SECTOR_FEED_SLICES tuple shape;
    the upstream default when the config list is empty."""
    entries = branding["feeds"]["sector_slices"]
    if not entries:
        return default
    return [
        (
            entry["filename"].strip(),
            _str_list(entry, "sectors", "sector_slices"),
            _str_list(entry, "tags", "sector_slices"),
            entry["title_suffix"].strip(),
            entry["description"].strip(),
        )
        for entry in entries
    ]


def trend_cohorts(
    branding: dict[str, Any],
    default: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """trends.cohorts in build.py's TREND_COHORTS dict shape; the upstream
    default when the config list is empty."""
    entries = branding["trends"]["cohorts"]
    if not entries:
        return default
    return [
        {
            "key": entry["key"].strip(),
            "title": entry["title"].strip(),
            "tags": _str_list(entry, "tags", "cohorts"),
            "sectors": _str_list(entry, "sectors", "cohorts"),
            "regions": _str_list(entry, "regions", "cohorts"),
            "match": (entry.get("match", "any") or "any").strip(),
        }
        for entry in entries
    ]
