#!/usr/bin/env python3
"""Build the static site bundle for GitHub Pages.

Reads:
    briefs/YYYY-MM-DD.md       (daily briefs)
    briefs/weekly/YYYY-Www.md  (weekly summaries)
    state/covered_items.json   (rolling coverage log)
    state/cves_seen.json       (flat CVE index)
    sources/sources.json       (curated source list)
    README.md                  (project overview)
    docs/*.md                  (workflow / verification / setup)

Writes everything the SPA needs into ./_site/:
    _site/index.html              (copied from ./index.html)
    _site/assets/...              (copied unchanged)
    _site/.nojekyll               (disable Jekyll on Pages)
    _site/briefs/<name>.md        (raw markdown, fetched on demand)
    _site/docs/<name>.md          (raw docs)
    _site/data/manifest.json      (brief metadata, newest first)
    _site/data/cves.json          (CVE list joined with brief appearances)
    _site/data/topics.json        (covered_items joined with brief paths)
    _site/data/sources.json       (sources joined with brief appearances)
    _site/data/search.json        (flat unified search index)
    _site/data/site.json          (build metadata: build time, counts)

Stdlib only. No build dependencies.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import sys
import urllib.parse
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = Path(__file__).resolve().parent
OUT = SITE / "_site"

CVE_RE = re.compile(r"\bCVE-\d{4}-\d{4,7}\b")
LINK_RE = re.compile(r"\[([^\]\n]+)\]\((https?://[^)\s]+)\)")
HEADER_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$", re.MULTILINE)


def slugify(text: str) -> str:
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", text.lower())).strip("-")


def verify_vendored_hashes() -> None:
    """Abort the build if any vendored library's bytes do not match HASHES.

    Catches both silent on-disk tampering (an attacker who got write access
    to the repo or the runner) and accidental version drift (a pull request
    that bumped a library without updating the integrity record). Only the
    SHA-256 line per file is enforced — sha384 in HASHES is for SRI use.
    """
    vendor = SITE / "assets" / "vendor"
    hashes_file = vendor / "HASHES"
    if not hashes_file.exists():
        print(f"warning: {hashes_file} missing; skipping integrity check", file=sys.stderr)
        return
    expected: dict[str, str] = {}
    for raw in hashes_file.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("//"):
            continue
        parts = line.split()
        if len(parts) != 3:
            continue
        algo, fname, digest = parts
        if algo == "sha256":
            expected[fname] = digest
    failures = []
    for fname, want in expected.items():
        path = vendor / fname
        if not path.exists():
            failures.append(f"{fname}: missing")
            continue
        got = hashlib.sha256(path.read_bytes()).hexdigest()
        if got != want:
            failures.append(f"{fname}: hash mismatch (expected {want}, got {got})")
    if failures:
        print("VENDORED LIBRARY INTEGRITY CHECK FAILED:", file=sys.stderr)
        for f in failures:
            print(f"  · {f}", file=sys.stderr)
        print(
            "Refuse to build a site with mismatched vendor bytes. "
            "If this is a deliberate upgrade, regenerate site/assets/vendor/HASHES.",
            file=sys.stderr,
        )
        sys.exit(2)


def host_of(url: str) -> str:
    try:
        h = urllib.parse.urlparse(url).hostname or ""
        return h.lower().lstrip("www.").strip()
    except Exception:
        return ""


def parse_brief(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    rel = str(path.relative_to(ROOT))
    name = path.stem  # YYYY-MM-DD or YYYY-Www
    is_weekly = path.parent.name == "weekly"

    # Title (first H1)
    m = re.search(r"^# (.+?)\s*$", text, re.MULTILINE)
    title = m.group(1).strip() if m else name

    # Generated-by metadata line (look for "Generated by:" or model marker)
    gen_match = re.search(r"\*\*Generated by:\*\*\s*([^\n·]+)", text)
    generated_by = gen_match.group(1).strip() if gen_match else None

    # Sections (H2 only, in order)
    sections = []
    for m in re.finditer(r"^## (.+?)\s*$", text, re.MULTILINE):
        heading = m.group(1).strip()
        sections.append({"heading": heading, "anchor": slugify(heading)})

    # TL;DR bullets — section 0
    tldr = []
    tldr_block = re.search(
        r"##\s*0\.\s*TL;DR\s*\n(.+?)(?=\n##\s|\Z)",
        text,
        re.DOTALL,
    )
    if tldr_block:
        for raw in tldr_block.group(1).splitlines():
            line = raw.strip()
            if line.startswith("- "):
                # Strip surrounding bold/italic markers but keep inline links — the SPA renders markdown
                tldr.append(line[2:].strip())

    # CVEs mentioned anywhere in the brief
    cves = sorted(set(CVE_RE.findall(text)))

    # Outbound links (deduped by URL, keep first label)
    links = []
    seen = set()
    for m in LINK_RE.finditer(text):
        label, url = m.group(1).strip(), m.group(2).strip()
        if url in seen:
            continue
        seen.add(url)
        links.append({"label": label, "url": url, "host": host_of(url)})

    # Item count = h3 headings (one per item) but only inside sections 1-4
    h3 = len(re.findall(r"^### .+$", text, re.MULTILINE))

    return {
        "name": name,
        "kind": "weekly" if is_weekly else "daily",
        "path": rel,
        "title": title,
        "generated_by": generated_by,
        "sections": sections,
        "tldr": tldr,
        "cves": cves,
        "links": links,
        "items": h3,
        "size": len(text),
    }


def collect_briefs() -> list[dict]:
    out = []
    daily_dir = ROOT / "briefs"
    weekly_dir = daily_dir / "weekly"
    for p in sorted(daily_dir.glob("*.md")):
        if not re.match(r"^\d{4}-\d{2}-\d{2}$", p.stem):
            continue
        out.append(parse_brief(p))
    if weekly_dir.exists():
        for p in sorted(weekly_dir.glob("*.md")):
            if not re.match(r"^\d{4}-W\d{2}$", p.stem):
                continue
            out.append(parse_brief(p))
    out.sort(key=lambda b: (b["kind"], b["name"]), reverse=True)
    return out


def annotate_sources(sources: dict, briefs: list[dict]) -> dict:
    """For each source, list briefs that cite it (matched by hostname).

    Mutates and returns the source list payload (the original sources.json shape)
    with an extra `appearances` array per source.
    """
    by_host: dict[str, list[str]] = defaultdict(list)
    for s in sources["sources"]:
        h = host_of(s["url"])
        if h:
            by_host[h].append(s["id"])

    src_appearances: dict[str, set[str]] = defaultdict(set)
    for b in briefs:
        for link in b["links"]:
            h = link["host"]
            if not h:
                continue
            # Exact host or any "endswith" match for subdomains.
            for shost, sids in by_host.items():
                if h == shost or h.endswith("." + shost):
                    for sid in sids:
                        src_appearances[sid].add(b["name"])

    enriched = []
    for s in sources["sources"]:
        appearances = sorted(src_appearances.get(s["id"], []), reverse=True)
        enriched.append({**s, "appearances": appearances})

    return {
        **sources,
        "sources": enriched,
    }


def annotate_cves(cves: dict, briefs: list[dict]) -> dict:
    by_id: dict[str, set[str]] = defaultdict(set)
    for b in briefs:
        for cve in b["cves"]:
            by_id[cve].add(b["name"])

    enriched = []
    seen_ids = set()
    for c in cves.get("cves", []):
        appearances = sorted(by_id.get(c["id"], []), reverse=True)
        enriched.append({**c, "appearances": appearances})
        seen_ids.add(c["id"])
    # Pick up any CVE found in briefs but missing from cves_seen.json (defensive)
    for cid, briefs_set in by_id.items():
        if cid in seen_ids:
            continue
        enriched.append(
            {
                "id": cid,
                "first_seen": min(briefs_set),
                "last_seen": max(briefs_set),
                "title": "",
                "primary_source_url": "",
                "appearances": sorted(briefs_set, reverse=True),
            }
        )
    enriched.sort(key=lambda c: c["last_seen"], reverse=True)
    return {**cves, "cves": enriched}


def annotate_topics(items: dict) -> dict:
    """The covered_items.json already carries `appearances` with brief paths.

    Normalize so the SPA can use a uniform `briefs` array of brief names.
    """
    enriched = []
    for it in items["items"]:
        names = []
        for app in it.get("appearances", []):
            bp = app.get("brief_path", "")
            m = re.search(r"(\d{4}-\d{2}-\d{2}|\d{4}-W\d{2})", bp)
            if m:
                names.append(m.group(1))
        names = sorted(set(names), reverse=True)
        enriched.append({**it, "briefs": names})
    enriched.sort(key=lambda i: i.get("last_covered", ""), reverse=True)
    return {**items, "items": enriched}


def build_search_index(
    briefs: list[dict],
    cves: dict,
    topics: dict,
    sources: dict,
) -> list[dict]:
    """Flat unified search index. Each entry:
        {kind, id, title, hint, briefs, route}
    The SPA does substring + token-prefix matching client-side.
    """
    idx = []

    for b in briefs:
        hint = " · ".join(b["tldr"][:2])[:240] if b["tldr"] else ""
        idx.append(
            {
                "kind": "brief",
                "id": b["name"],
                "title": b["title"],
                "hint": hint or f"{b['kind'].capitalize()} brief · {b['items']} items",
                "tags": [b["kind"]] + b["cves"][:6],
                "route": f"#/briefs/{b['name']}",
            }
        )

    for c in cves["cves"]:
        idx.append(
            {
                "kind": "cve",
                "id": c["id"],
                "title": c["id"],
                "hint": c.get("title", "")[:240],
                "tags": [],
                "route": f"#/cves/{c['id']}",
            }
        )

    for t in topics["items"]:
        idx.append(
            {
                "kind": "topic",
                "id": t["key"],
                "title": t["title"],
                "hint": f"{t['type']} · last covered {t.get('last_covered','?')}",
                "tags": [t["type"]],
                "route": f"#/topics/{urllib.parse.quote(t['key'], safe='')}",
            }
        )

    for s in sources["sources"]:
        cats = ", ".join(s.get("category", []))
        idx.append(
            {
                "kind": "source",
                "id": s["id"],
                "title": s["publisher"],
                "hint": f"{s['reliability']} · {cats}",
                "tags": s.get("category", []) + [s.get("reliability", ""), s.get("status", "")],
                "route": f"#/sources/{urllib.parse.quote(s['id'], safe='')}",
            }
        )

    return idx


def copy_tree(src: Path, dst: Path):
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def cachebust_index(index_path: Path) -> str:
    """Append ?v=<fingerprint> to every asset URL in index.html.

    The fingerprint is the first 10 hex chars of a SHA-256 over the byte
    contents of every .js / .css file under assets/. When any asset
    changes, the fingerprint changes, the URLs change, and the browser
    bypasses its on-disk cache for those URLs immediately. This stops the
    "old JS still served from cache after a deploy" failure mode that
    surfaces as readers seeing yesterday's bugs.

    Vendored libs are included in the hash so a marked.js or DOMPurify
    upgrade also forces a refresh.

    Returns the fingerprint so the caller can log it.
    """
    assets_dir = index_path.parent / "assets"
    h = hashlib.sha256()
    for p in sorted(assets_dir.rglob("*")):
        if p.is_file() and p.suffix in (".js", ".css"):
            h.update(p.read_bytes())
    fingerprint = h.hexdigest()[:10]

    html = index_path.read_text()

    def add_v(match: re.Match) -> str:
        prefix, attr, url = match.group(1), match.group(2), match.group(3)
        if "?" in url:
            return match.group(0)
        return f'{prefix}{attr}="{url}?v={fingerprint}"'

    html = re.sub(
        r'(<(?:script|link)[^>]*?\s)(src|href)="(assets/[^"]+\.(?:js|css))"',
        add_v,
        html,
    )
    index_path.write_text(html)
    return fingerprint


def main() -> int:
    if not (ROOT / "briefs").exists():
        print(f"error: no briefs/ directory at {ROOT}", file=sys.stderr)
        return 1

    verify_vendored_hashes()

    OUT.mkdir(exist_ok=True)
    # Wipe and recreate _site/ for deterministic builds.
    for child in OUT.iterdir():
        if child.is_dir():
            shutil.rmtree(child)
        else:
            child.unlink()

    # 1. Copy SPA shell.
    shutil.copy(SITE / "index.html", OUT / "index.html")
    copy_tree(SITE / "assets", OUT / "assets")
    (OUT / ".nojekyll").write_text("")

    # 1a. Cache-bust the asset URLs in the copied index.html so post-deploy
    #     stale-cache misses (Pages serves index.html with max-age=600 too)
    #     don't strand readers on yesterday's JS forever. Only the URLs
    #     change; the on-disk filenames stay stable so the SPA's relative
    #     paths still resolve.
    fp = cachebust_index(OUT / "index.html")

    # 2. Copy briefs (raw markdown, fetched on demand by the SPA).
    briefs_out = OUT / "briefs"
    briefs_out.mkdir(exist_ok=True)
    for p in (ROOT / "briefs").glob("*.md"):
        if re.match(r"^\d{4}-\d{2}-\d{2}\.md$", p.name):
            shutil.copy(p, briefs_out / p.name)
    weekly_dir = ROOT / "briefs" / "weekly"
    if weekly_dir.exists():
        (briefs_out / "weekly").mkdir(exist_ok=True)
        for p in weekly_dir.glob("*.md"):
            if re.match(r"^\d{4}-W\d{2}\.md$", p.name):
                shutil.copy(p, briefs_out / "weekly" / p.name)

    # 3. Copy README and docs (rendered as About / docs pages).
    docs_out = OUT / "docs"
    docs_out.mkdir(exist_ok=True)
    shutil.copy(ROOT / "README.md", docs_out / "README.md")
    if (ROOT / "briefs" / "README.md").exists():
        shutil.copy(ROOT / "briefs" / "README.md", docs_out / "briefs-README.md")
    for p in (ROOT / "docs").glob("*.md"):
        shutil.copy(p, docs_out / p.name)

    # 4. Build data bundle.
    data_out = OUT / "data"
    data_out.mkdir(exist_ok=True)

    briefs = collect_briefs()
    cves_raw = json.loads((ROOT / "state" / "cves_seen.json").read_text())
    topics_raw = json.loads((ROOT / "state" / "covered_items.json").read_text())
    sources_raw = json.loads((ROOT / "sources" / "sources.json").read_text())

    sources = annotate_sources(sources_raw, briefs)
    cves = annotate_cves(cves_raw, briefs)
    topics = annotate_topics(topics_raw)

    (data_out / "manifest.json").write_text(json.dumps(briefs, indent=2))
    (data_out / "cves.json").write_text(json.dumps(cves, indent=2))
    (data_out / "topics.json").write_text(json.dumps(topics, indent=2))
    (data_out / "sources.json").write_text(json.dumps(sources, indent=2))
    (data_out / "search.json").write_text(
        json.dumps(build_search_index(briefs, cves, topics, sources))
    )

    site_meta = {
        "built_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "counts": {
            "briefs": len(briefs),
            "daily": sum(1 for b in briefs if b["kind"] == "daily"),
            "weekly": sum(1 for b in briefs if b["kind"] == "weekly"),
            "cves": len(cves["cves"]),
            "topics": len(topics["items"]),
            "sources": len(sources["sources"]),
        },
    }
    (data_out / "site.json").write_text(json.dumps(site_meta, indent=2))

    print(f"built {OUT} · {site_meta['counts']} · cachebust=v={fp}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
