# Check Point 93616
add('793e3cbd50','bf','One exploit ran end to end against both unpatched hosts, confirming root on each, self-contained over the exposed port.')
add('de2bd77999','cpb','As of the advisory publications date, we observed a handful of pinpointed attacks on July 23, 2026.','F14')
add('7a5d1ff534','sk','Because of the nature of the fix, a LivePatch is not be available for this issue.')
add('4e299eebea','sk','Make sure that access to port TCP/19009 is only possible from Trusted IP addresses.')
add('128a418027','bf','`authorized_keys` and the usual startup paths, which any root write reaches.')
add('62af9ba2cb','sk','This problem was fixed.','F4')
add('568680e463','sk','allows an unauthenticated attacker to upload and execute arbitrary scripts on the Check Point Management Server')
add('ba8c9bedc1','cpb','allows an attacker to execute a script from an arbitrary path and load an arbitrary Java class')
add('dcebb82077','cpb','As of the advisory publications date, we observed a handful of pinpointed attacks on July 23, 2026.')
add('1fbe34e55c','sk','Because of the nature of the fix, a LivePatch is not be available for this issue.')
add('83b9e22a45','thn','Check Point says those LivePatch takes do not fix CVE-2026-93616.')
add('11edb1c7e8','kev','DERIVED: live KEV (catalogVersion 2026.10.02) lists CVE-2026-93616 dateAdded 2026-09-22')
add('66e8085052','cpb','Check Point disclosed the vulnerability and released fixes on September 9, 2026.')
add('5c80850171','sk','Check for these two indicators of compromise on every Security Management')
add('e8578426a9','bf','whose crash signature, an over-long username next to a core dump, is the advisory\u2019s first indicator, not evidence of this traversal.')
add('071a0ff3c7','bf','It fires only when an upgrade-tools load fails, which makes it a weak net both ways.')
add('4c51b0d291','sk','Make sure that access to port TCP/19009 is only possible from Trusted IP addresses.')
add('a3a64f86cc','bf','Execution runs as root inside the process that holds your policy and internal CA.')
add('f878cc9a1e','sk','Smart-1 Cloud (fix is already applied)')
add('dcd09d8b36','sk','R82.10 Jumbo Hotfix Take 44 or lower')
add('c47d488b88','bf','The fix ships in Jumbo Hotfix Accumulator R82.10 Take 45, R82 Take 127, R81.20 Take 170, and R81.10 Take 192, and in the R82.20 Security Hotfix.')
add('ae7bf3a4cf','cpb','As of the advisory publications date, we observed a handful of pinpointed attacks on July 23, 2026.','F14')
add('e97e2f6ef2','bf','We reproduced the attack end to end against unpatched R81.10 and R82.10 lab servers')
add('7fd49c3889','bf','Overwriting it with a crontab fragment runs an attacker\u2019s command as root on the next minute boundary.')
add('6b960579cf','bf','Closing any single one would leave the others standing.')
add('bdf67428aa','bf','Either fix alone breaks the chain; Take 45 ships both, plus the `targetVersion` validation.')
add('647afa3052','bfgh','does not detect prior compromise')
add('4981327ddf','bf','A genuine upgrade can trip the grep on its own.')
add('9851829d8e','bf','Pair file checks with execution telemetry, cron reload events, and an alert on the CPM Java process spawning a shell.')
add('e1156cffb3','bf','The second is a permissions setting, not a rule base entry, so a rule base audit alone can miss it.')
add('b2011a4af1','bf','Our proof-of-concept script returned `uid=0(admin) gid=0(root)` on both of our unpatched lab servers, R81.10 and R82.10.')
add('6914180c1a','bf','If a user network can reach an unpatched management server, treat it as though it\u2019s already compromised.')
add('052e98c83a','bf','whose crash signature, an over-long username next to a core dump, is the advisory\u2019s first indicator, not evidence of this traversal.')
# Flink
add('a083780bba','fnl','The LPG Group is not particularly well-known, and their origins have not yet been reported.')
add('ed614997f9','fnl','Since its founding five years ago, the company started up and wound down operations in both Austria and France.')
add('b9a3d580ad','fheise','Durch diese Strukturen kann der Dienst sein Versprechen einer Lieferung in unter einer halben Stunde meist erf\u00fcllen.')
add('432c018c64','frn','Nach Angaben des Berliner Unternehmens gelangte eine unbefugte Person mithilfe kompromittierter Zugangsdaten in eines der internen Systeme des Lieferdienstes.')
add('c61c56a02f','fheise','Laut Flink wurde ein einzelner dieser Order Hubs angegriffen, dieser wurde auch schon identifiziert und der unberechtigte Zugriff unterbunden.')
add('e6ebacc5e0','fheise','Auf Nachfrage hie\u00df es, dass Flink auch in diesem Fall tats\u00e4chlich gar nicht reagiert hat.')
add('8bb8cf5ba6','fnl','The total number of affected customers was not confirmed by Flink, but one million would represent two-thirds of their customer base, according to information Flink released in June.')
add('2d92a465c7','fheise','Wenn der Betrag zusammenkommt, so das Versprechen, w\u00fcrden die Daten gel\u00f6scht.')
add('34e9d7379a','fheise','Die Mails wenden sich namentlich und mit einem Flink-\u00e4hnlichen gef\u00e4lschten Absender an die Kunden, sodass diese wohl leicht verunsichert werden k\u00f6nnten.')
add('b0c4b9c07b','fnl','Flink stressed that account passwords, billing information, bank account details, and payment cards were not compromised.')
add('cab7161efa','fnl','"But I haven\'t seen individual consumers being approached before," said Takkenberg in an interview with NOS.')
add('e44d6b79f9','fheise','Anders als urspr\u00fcnglich gemeldet hat Flink eigenen Angaben zufolge bisher nicht das BSI eingeschaltet.')
add('364b6895f3','fnl','has filed reports with police there and in the Netherlands, a company spokesperson said.')
add('75ef6c8c3f','fheise','wandten sich die Angreifer zun\u00e4chst an Flink direkt und forderten Geld in Form der Kryptow\u00e4hrung ETH.')
add('1637cb4923','fheise','Daher wandten sich die Kriminellen nun direkt an die Kunden')
add('5b1050238f','fheise','gingen dort bei mindestens 10.000 Kunden Erpressermails ein.')
add('31198ccea9','fnl','Hacker group Shinyhunters did extort Dutch higher education institutions that were the clients of a hacked software system.')
add('ffd7bc4291','fheise','Laut Flink wurde \u00fcber eine Abuse-Mitteilung beim von der Bande genutzten Mailprovider die Flut der Schreiben auch vorerst einged\u00e4mmt')
add('9107100556','fheise','Keine Antwort und Anzeige bei der Polizei ist der einzig richtige Weg.')
add('66d56675e0','fheise','Keine Antwort und Anzeige bei der Polizei ist der einzig richtige Weg.')
add('e3ccc2e1ae','fheise','Die Erpresser haben sich also bei einem zahlungsunwilligen Unternehmen auf eine Art kriminelles Crowdfunding verlegt.')
add('41ab64aee9','frn','Nach Angaben des Berliner Unternehmens gelangte eine unbefugte Person mithilfe kompromittierter Zugangsdaten in eines der internen Systeme des Lieferdienstes.')
add('a55fdec48f','fheise','gingen dort bei mindestens 10.000 Kunden Erpressermails ein.')
add('b4ec912a1a','fnl','We are aware that criminals are currently attempting to exploit this incident by contacting customers and employees directly and requesting payments.')
add('30f64b4568','fnl','if the company itself pays an extortion demand of 100 ETH, which is just shy of 237,300 euros.')
add('e7dc519350','frn','Nach Angaben des Berliner Unternehmens gelangte eine unbefugte Person mithilfe kompromittierter Zugangsdaten in eines der internen Systeme des Lieferdienstes.')
# Citrix 88771
add('3613aefa62','wt','attackers exploited as zero-days, before any fix existed.')
add('1f570a7718','gtig','The DTLS and UDP/443 controls below are specific to CVE-2026-88772 and should not be relied on to mitigate CVE-2026-88771.')
add('f078b476fb','wt','On 13.1, run `show ns variable` first: if it returns any variables, use 13.1-64.24 to avoid a known reboot loop during the upgrade.')
add('49aa0d8eff','gtig','Disable configuration synchronization until both nodes have been validated to prevent a compromised node from replicating malicious changes')
add('5e4c8a48ee','tenable','NetScaler ADC and NetScaler Gateway versions 12.1 and 13.0 have reached end-of-life (EOL) and no longer receive security updates, and Citrix has not said whether they are affected by these vulnerabilities.')
add('48ab05cd03','wt','attackers exploited as zero-days, before any fix existed.')
add('69be7f2e4c','ctx096','Exploits of CVE-2026-88771 and CVE-2026-88772 on unmitigated NetScaler deployments have been observed.')
add('30bb01b9e8','kev','DERIVED: live KEV lists CVE-2026-88771/88772 dateAdded 2026-09-27, forensicTriage Yes, BOD 26-04 requiredAction')
add('ff0f929be7','certeu','CERT-EU strongly advise to run a compromise assessment on any internet-facing appliance running an affected build.')
add('cb05e92189','bc','The agency declined to confirm the notification, saying it could not provide further information to organizations outside its constituency.')
add('f78239f07d','ncslnl','1.0.0 | 27-09-2026 16:55 | Initiele versie')
add('375d1894db','wt','No attribution has been made public. Historically, NetScaler vulnerabilities have been exploited by both state-sponsored groups and ransomware operators.')
add('8f9351d61d','wt','Appliances patched for CVE-2026-19490 remain vulnerable to CVE-2026-88771 and CVE-2026-88772 unless they run one of the fixed builds above.')
add('648420dd0b','wt','Citrix has not published a workaround for either vulnerability, so upgrading is the only fix.')
add('bd5077c6f6','wt','Capture logs, a snapshot, a support bundle and a core dump from each exposed appliance.')
add('dae7c16c7a','kev','DERIVED: live KEV entry for CVE-2026-88771 has forensicTriage Yes and notes "Customers must conduct forensic triage as directed by BOD 26-04"')
add('fca670b72b','wt','Citrix warns that the IOCs do not cover every technique, so a clean result is not proof that an appliance was not compromised.')
add('05b2a64afd','certat','Laut Hersteller werden CVE-2026-88771 und CVE-2026-88772 bereits aktiv ausgenutzt.')
add('d31e164167','csh','"created": "2026-09-28T05:39:47.423456Z"')
add('ffff8517f1','ctx096','CWE-20: Improper Input Validation | CVSS v4.0 Base Score: 9.5')
add('c243414a20','ctx096','(Note: Enabled by default on VPN vServer)')
add('ef28f1a35c','bc','The first signs of the incident appeared when Citrix administrators began reporting on Reddit that IT suppliers and security teams were privately contacting their organizations and advising them to shut down their NetScaler appliances.')
add('1828124b39','ctx096','CWE-342: Predictable Exact Value from Previous Values | CVSS v4.0 Base Score: 8.8')
add('c2261fa5ca','wt','On 13.1, run `show ns variable` first: if it returns any variables, use 13.1-64.24 to avoid a known reboot loop during the upgrade.')
add('4b4f4ff745','ctx174','NetScaler ADC and NetScaler Gateway 14.1-73.41 and later releases')
add('187baa5776','u42','pitboss PPE missed too many heartbeatsNSPPE;<additional text>')
add('573116ad17','gtig','A matching DTLS handshake failure followed within minutes by an NSPPE termination/crash on the same appliance is a strong exploitation signal and should be investigated with high priority.')
add('4a1248e2c5','wt','Memory overflow that can lead to remote code execution or denial of service when DTLS is enabled (the default for VPN virtual servers).')
add('55d99d951c','cblog','Citrix has observed targeted attacks on unmitigated NetScaler deployments which can lead to Denial of Service.')
add('a2627c3438','cguid','This issue is independent of the vulnerabilities disclosed in')
add('970de6ef4c','cblog','please upgrade your deployment again with the software released as part of the')
add('b153c841b0','ctx174','NetScaler ADC 13.1-FIPS and 13.1-NDcPP 13.1-37.282 and later releases of 13.1-FIPS and 13.1-NDcPP')
add('3b60bd91ae','cblog','NetScaler ADC and NetScaler Gateway 14.1 before 14.1-73.41')
add('25a93814d2','cblog','Citrix has observed targeted attacks on unmitigated NetScaler deployments which can lead to Denial of Service.')
# Zammad
add('f97c742eab','d14','We explain the attackers got in through two zero-days in Zammad that together allowed session hijacking, remote code execution and privilege escalation from the Zammad user to root, in seconds due to the agentic part of this hack.')
add('22fc75a5db','zst','we cannot confirm the vulnerability, its scope or the affected versions at this time.')
add('5d7305f8c5','d15','We advise all users of Zammad to upgrade to version 7 of Zammad or to take it offline.')
add('c787a2603b','d14','Thanks to proper network segmentation and the actions of our IT and Incident Response Team after detection, we were able to stop the attackers from going deeper into our systems and network.')
add('9e31060113','c489','In Zammad versions 6.3.0 to 6.5.4 are vulnerable a remote code execution as a Zammad user')
add('9349fe34a8','c490','All versions of Zammad including the latest alpha enable the local zammad user to escalate privileges to root.')
add('f2e531b28b','d14','We explain the attackers got in through two zero-days in Zammad that together allowed session hijacking, remote code execution and privilege escalation from the Zammad user to root, in seconds due to the agentic part of this hack.')
add('e08e502feb','d14','What we know for sure is that volunteer data got out, such as DIVD email addresses and possibly contact details.')
add('b2d4026edc','d14','We see no link to any known public threat actor')
add('a03b8b036c','d15','The vulnerability is also present in version 7.0.0 to version 7.1.3, but not exploitable due to environment conditions.')
add('5bf3603018','zncsc','maakt het mogelijk dat een aanvaller zonder in te loggen op afstand schadelijke code kan uitvoeren')
add('e86f7e914c','c489','CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:H/VI:H/VA:H/SC:L/SI:L/SA:L/E:A/AU:Y/V:C')
add('b4ed953885','c490','CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H/E:A/AU:Y/V:C')
add('26e44287d0','zncsc','De tweede kwetsbaarheid (CVE-2026-102490) is nog niet opgelost.')
add('8d3bc89b4b','d15','DIVD is actively scanning and alerting owners of vulnerable Zammad instances.')
add('38e5f00699','zst','Exploitation is only possible on Zammad 6.5 and older, because of the runtime environment those versions use.')
add('efd79180b7','d15','to check your Zammad logfiles for Indicators of Compromise')
add('02771335ff','zncsc','Maak voor het installeren van de update een kopie van de applicatie- en netwerklogs.')
add('ac6baa75e9','zst','If you still run Zammad 6.5 or older, update now.')
add('d415ac24c9','','ABSENT: none of the statement, DIVD pages or NCSC-NL alert says whether hosted Zammad is affected')
add('e2bbea9661','d14','From there they could access other services and exfiltrate data.')
add('1f9a7a98ab','zncsc','Hierdoor kan een aanvaller het systeem overnemen, gegevens bekijken, aanpassen of verwijderen en het systeem gebruiken voor verdere aanvallen.')
add('28dc2313a7','kev','DERIVED: live KEV lists CVE-2026-102489 and CVE-2026-102490 dateAdded 2026-10-02; shortDescription "can be chained with CVE-2026-102490/102489"')
add('662005ff4e','zst','We have still hardened the affected code. The change is included in Zammad 7.2.0.')
add('3ef1010d4e','zst','DIVD\u2019s own timeline shows a report to us on 24 September 2026, followed by public scanning and disclosure on 26 September 2026.')
add('195d515716','zst','We first received a report about this issue in August 2026 and analysed it then.')
add('33a2b4edb9','zst','We first received a report about this issue in August 2026 and analysed it then.')
# 88779
add('e74d8bce49','cblog','Citrix has observed targeted attacks on unmitigated NetScaler deployments which can lead to Denial of Service.')
add('db42895391','ctx174','NetScaler ADC or NetScaler Gateway must be configured as a SAML SP OR SAML IdP')
add('26a647db4c','cblog','The version number needs to be at least v24 as shown below:')
add('06b37367c7','cguid','If you are currently experiencing the impact from this issue, please contact Citrix support.')
add('8163bd6e31','ctx174','CVSS v4.0 Base Score: 8.7 CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N')
add('d7c87f0a1a','ctx174','CVSS v4.0 Base Score: 8.7 CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N')
add('9f233963c9','cblog','we have not identified an impact on the integrity of customer data.')
add('58e6cfc748','cguid','This issue is independent of the vulnerabilities disclosed in')
add('9186b4a224','cblog','please upgrade your deployment again with the software released as part of the')
add('80a625e4a8','ctx174','NetScaler ADC 14.1-FIPS 14.1-73.41 FIPS and later releases of 14.1-FIPS')
add('4785385451','cblog','Please also note that the Global Deny List signatures can help to mitigate the vulnerability.')
add('cd31a1d344','cyber','Multiple administrators said malicious or malformed SAML-related requests appeared to crash the `nsaaad` authentication service, triggering failovers or full appliance reboots.')
add('4c6cdfd5de','heisens','So on one of the honeypots it\u2019s running a downloaded (malware) binary.')
add('d4a1afd069','acsc','A remote attacker exploiting the issue may induce system crashes, denial of service and potential exploitation.')
add('8f92b52871','kev','DERIVED: live KEV (catalogVersion 2026.10.02) has no CVE-2026-88779; heise carries Beaumont honeypot quote and watchTowr reproduction only')
add('58a78e2cc1','ctx174','Additional Note: Secure Private Access Hybrid deployments using NetScaler instances are also affected by the vulnerabilities.')
add('20b8043e2c','cblog','The issue is associated with NetScaler deployments that use SAML authentication in conjunction with Gateway or AAA functionality.')
add('be9c65fc4d','cyber','One administrator reported seeing an apparent command intended to download a script in appliance logs, although the download did not succeed.')
add('5e0c2201a8','cyber','the combination of active scanning, malformed authentication traffic, and appliance crashes warrants incident-response handling until forensic analysis rules out intrusion.')
add('363e6d42d3','heisens','Zero-day causes crashes and code execution')
add('fd97aa4056','heisens','The exploit can likely be executed by sending a massive number of SAML requests to a vulnerable device.')
add('667acbee7d','cblog','Citrix recommends upgrading to the following software versions containing the fix as soon as possible.')
add('cf75da4c0d','cyber','The incidents have been reported on internet-facing NetScaler ADC and Gateway appliances running patched releases, including version 14.1-73.37.')
# ChatGPT
add('2c7b5ca0a6','hgpt','In the incidents we saw, victims interacted with an attacker-created Custom GPT, which was programmed to respond to their prompts with a message that included a Google Sites link.')
add('49d5362d99','hgpt','In some of the incidents that we investigated, the attack started when victims searched on Google for "chatgpt." A sponsored result then led them to the Custom GPT page on the legitimate ChatGPT domain.')
add('55b5986bf6','hgpt','rules and URL filters that look for a dotted IP address never see one.')
add('cf22ea502a','hgpt','so they never appear in local DNS logs.')
add('da1d39150d','hgpt','Huntress reached out to OpenAI regarding this specific Custom GPT, and it was taken down as of September 25')
add('aa14b9f248','hgpt','Detections tied to Canon or Stardock names will miss the next swap. The behaviors (so far) carry over:')
add('aecea88481','hgpt','A Run value and scheduled task that share one name and come back when deleted')
add('ab01c27a52','hgpt','Kill the process first, then remove both.')
add('d395faf728','hgpt','Attackers titled this Custom GPT "Plus 5.6" so that an unsuspecting visitor would mistake it for an actual ChatGPT model.')
add('bad5568119','hgpt','This Google Sites page presents as a CloudFlare CAPTCHA check and delivers a ClickFix attack, telling users to copy-and-paste a command into their Terminal.')
add('b311360bdd','hgpt','introduces itself as "Advanced Printer Configuration Reader"')
add('88af8fb781','hgpt','Hosting the .NET runtime (CLR v4.0.30319), which lets it run .NET code straight from memory without dropping an assembly to disk')
add('d1e016c764','hgpt','Every 150 seconds, the script checks for that Run key and re-creates it if it\'s gone, and every 875 seconds it does the same for a scheduled task.')
add('6364f40a64','hgpt','has responded to at least 40 incidents stemming from the specific Google Sites domain involved in this attack, and confirmed that two of these incidents came through a Custom GPT instance')
add('0621ab86a0','hgpt','telling users to copy-and-paste a command into their Terminal.')
add('dec37f9d8e','hgpt','Most of this chain runs in memory or hides inside files that look harmless, so process activity is the most reliable place to catch it:')
add('676b9ff6f4','hgpt','A signed app started by msiexec from a fake product folder')
add('888545c871','hgpt','the RAT uses DNS-over-HTTPS through Cloudflare, Google, and Quad9 servers.')
add('d6eede2fdf','hgpt','Detections tied to Canon or Stardock names will miss the next swap.')
# Recreation
add('5864f42acc','hpk','After registering a new account on the platform, the attacker was able to upload malicious files directly to the')
add('d1c88c267d','hpk','Huntress observed a threat actor compromising multiple tenants on a shared recreation management software platform using one repeatable trick')
add('fd9b1d0914','hpk','register a member account, upload a malicious file, and turn it into a webshell.')
add('8fc02818c0','hpk','The attacker uploaded 14 files to the `/documents/MemberFiles/` directory, including `.aspx`, `.jpg`, and `.pdf` formats.')
add('63c84c2cb7','hpk','attempted automated file reading before manually dumping specific log files to extract payment card details, including expiration dates, CVVs, and credit card numbers.')
add('c4079811ab','hpk','This attempt failed, with no webshells detected within the payment modules directories.')
add('1cf3634c2d','hpk','The attacker intended to convert every visiting browser to `/auth/default.aspx` into an encrypted C2 client.')
add('ab1efd70dd','hpk','After registering a new account on the platform, the attacker was able to upload malicious files directly to the')
add('aae3e9c834','hpk','before being decoded into actual `.ps1` and `.js` files.')
add('bdafc097e6','hpk','The `.jpg` and `.pdf` files were uploaded as an extension execution test; only the `.aspx` files were used to execute commands.')
add('2c6895a8d8','hpk','walked straight back in after a server was cleaned but not fully locked down.')
add('0866c0d8a5','hpk','breach 3 municipal servers and steal payment data.')
add('573aa0675a','hpk','From here, we can deduce that the threat actor is most likely based in China.')
add('6f05f1fc7f','','ABSENT: the post gives no count of exposed cards and no exfiltration statement; its page description says "steal payment data"')
add('44217662be','hpk','The `.aspx` webshells executed enumeration commands on the server, giving the attacker the lay of the land')
add('6837e8b606','hpk','With their eye on payment transaction logs generated by a Fortis webhook integration')
