#!/usr/bin/env python3
"""Keep the registry's `product:` records in step with the entry store.

Every entry names the software it concerns in `affected_products[]`, at the
precision a responder needs ("Microsoft SharePoint Server 2019"). That is the
wrong granularity for a pivot: a reader asking "what has happened to
SharePoint?" wants one page, not one per release. This tool turns those
strings into PRODUCT ENTITIES so a product sits beside actors, malware and
campaigns, with its own permalink, coverage timeline, ATT&CK profile and node
in the threat graph.

  python3 tools/sync_products.py            # write the block
  python3 tools/sync_products.py --check    # report drift, exit 1 if any
  python3 tools/sync_products.py --report   # what resolved where

What it writes: one contiguous, marked block of `product:` records at the end
of `entities/registry.yaml`. Everything else in that file is untouched, so
the diff is the products and nothing else.

What it preserves: every curated field on an existing product record —
`name`, `summary`, `aliases`, `relations`, `merged_into`, `first_seen`. The
tool only ADDS the spellings it found in the corpus. Merging two products is
therefore an edit, not a migration: add the loser's name to the winner's
`aliases` (or tombstone it with `merged_into`) and re-run; the entries that
named the old spelling follow, because they were never rewritten.

Registry keys are permanent. This tool never renames one.
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "site"))

import content_model  # noqa: E402

REGISTRY_PATH = ROOT / "entities" / "registry.yaml"

BLOCK_START = (
    "  # ---------------------------------------------------------------------\n"
    "  # PRODUCTS — affected software as entities.\n"
    "  #\n"
    "  # Generated by tools/sync_products.py from every entry's\n"
    "  # affected_products[]; curated fields (name, summary, aliases,\n"
    "  # relations, merged_into) are read back and preserved, so merging two\n"
    "  # spellings means adding an alias here, never editing an entry.\n"
    "  # ---------------------------------------------------------------------\n"
)
BLOCK_END = "  # --- end PRODUCTS ---\n"

# Seed merges: product families the mechanical rule cannot fold, because the
# difference is a marketing name rather than a version. Canonical name ->
# every spelling the corpus uses for the same product line. Each becomes the
# record's `aliases`, after which resolution is purely registry-driven.
#
# Only same-product-line merges belong here. Two SKUs a vendor advises
# together are still two products (Fortinet FortiOS and FortiProxy stay
# apart); a release codename, an "Enterprise Server" spelling or a renamed
# suite is one product.
SEED_ALIASES: dict[str, list[str]] = {
    "Microsoft SharePoint": [
        "Microsoft SharePoint Server",
        "Microsoft SharePoint Server Subscription Edition",
        "Microsoft SharePoint Server 2019",
        "Microsoft SharePoint Server 2016",
        "Microsoft SharePoint Enterprise Server 2016",
        "SharePoint Server",
        "SharePoint",
    ],
    "Microsoft Exchange Server": [
        "Microsoft Exchange Server Subscription Edition",
        "Microsoft Exchange Server 2019",
        "Microsoft Exchange Server 2016",
        "Exchange Server",
    ],
    "Microsoft Windows": [
        "Microsoft Windows 11",
        "Microsoft Windows 10",
    ],
    "Microsoft Defender Antivirus": [
        "Microsoft Windows Defender",
        "Microsoft Defender",
        "Windows Defender",
    ],
    "Microsoft Graph": ["Microsoft Graph API"],
    "Apple macOS": [
        "Apple macOS Tahoe",
        "Apple macOS Sequoia",
        "Apple macOS Sonoma",
    ],
    "Citrix NetScaler": [
        "Citrix NetScaler ADC",
        "Citrix NetScaler Gateway",
        "NetScaler ADC",
        "NetScaler Gateway",
    ],
    "Zimbra Collaboration": [
        "Zimbra Collaboration Suite",
        "Zimbra Collaboration Suite Classic Web Client",
        "Zimbra Collaboration Suite (Classic Web Client)",
        "Zimbra Classic Web Client",
    ],
    "SonicWall SMA 1000": [
        "SonicWall SMA1000",
        "SonicWall Secure Mobile Access (SMA) 1000",
        "SonicWall SMA",
    ],
    "Rockwell Automation MicroLogix": [
        "Rockwell Automation Allen-Bradley MicroLogix 1100",
        "Rockwell Automation Allen-Bradley MicroLogix 1400",
        "Rockwell Automation MicroLogix 1100",
        "Rockwell Automation MicroLogix 1400",
    ],
    "Rockwell Automation 1715-AENTR": [
        "Rockwell Automation 1715-AENTR EtherNet/IP Adapter",
    ],
    "Cisco IOS XE": ["Cisco IOS XE Software"],
    "VMware ESXi": ["VMware ESX"],
}


def _existing_products(registry: dict) -> dict[str, dict]:
    return {
        k: v for k, v in registry.items()
        if isinstance(v, dict) and str(v.get("type") or "") == "product"
    }


def _seed_index() -> dict[str, tuple[str, str]]:
    """folded spelling -> (canonical key, canonical display name)."""
    out: dict[str, tuple[str, str]] = {}
    for name, aliases in SEED_ALIASES.items():
        key = f"product:{content_model.slugify(name)}"
        for label in [name, *aliases]:
            out[content_model._fold_product_label(label)] = (key, name)
    return out


def build_records(entries: list[dict], registry: dict) -> tuple[list[dict], dict[str, str]]:
    """(product records in key order, raw string -> resolved key)."""
    existing = _existing_products(registry)
    alias_index = content_model.product_alias_index(registry)
    seed = _seed_index()

    # key -> record under construction
    recs: dict[str, dict] = {}
    for key, ent in existing.items():
        recs[key] = {
            "key": key,
            "type": "product",
            "name": str(ent.get("name") or key.split(":", 1)[-1]),
            "aliases": [a for a in (ent.get("aliases") or []) if isinstance(a, str)],
            "summary": str(ent.get("summary") or ""),
            "first_seen": str(ent.get("first_seen") or ""),
            "merged_into": str(ent.get("merged_into") or ""),
            "relations": [r for r in (ent.get("relations") or []) if isinstance(r, dict)],
        }

    resolved: dict[str, str] = {}
    raw_dates: dict[str, list[str]] = defaultdict(list)
    for e in entries:
        for raw in e.get("affected_products") or []:
            raw = re.sub(r"\s+", " ", str(raw or "")).strip()
            if not raw:
                continue
            raw_dates[raw].append(str(e.get("date") or ""))

    for raw in sorted(raw_dates):
        folded = content_model._fold_product_label(raw)
        key = alias_index.get(folded, "")
        name = ""
        if not key:
            hit = seed.get(folded)
            if hit:
                key, name = hit
        if not key:
            key = content_model.product_key(raw)
            name = content_model.product_display_name(raw)
        if not key:
            resolved[raw] = ""      # vendor-only string: never an entity
            continue
        rec = recs.get(key)
        if rec is None:
            rec = recs[key] = {
                "key": key, "type": "product",
                "name": name or content_model.product_display_name(raw),
                "aliases": [], "summary": "", "first_seen": "",
                "merged_into": "", "relations": [],
            }
        if raw != rec["name"] and raw not in rec["aliases"]:
            rec["aliases"].append(raw)
        first = min(d for d in raw_dates[raw] if d) if any(raw_dates[raw]) else ""
        if first and (not rec["first_seen"] or first < rec["first_seen"]):
            rec["first_seen"] = first
        resolved[raw] = key

    # Seed aliases that the corpus has not produced yet still belong on the
    # record: they are the merge instruction, not an observation.
    for name, aliases in SEED_ALIASES.items():
        key = f"product:{content_model.slugify(name)}"
        rec = recs.get(key)
        if rec is None:
            continue
        for a in aliases:
            if a != rec["name"] and a not in rec["aliases"]:
                rec["aliases"].append(a)

    for rec in recs.values():
        rec["aliases"] = sorted(set(rec["aliases"]))
    return [recs[k] for k in sorted(recs)], resolved


def render_block(records: list[dict]) -> str:
    out = [BLOCK_START]
    for r in records:
        out.append(f'  - key: "{r["key"]}"\n')
        out.append("    type: product\n")
        out.append(f'    name: {content_model._dump_scalar(r["name"])}\n')
        aliases = r["aliases"]
        if aliases:
            out.append("    aliases: [" + ", ".join(
                content_model._dump_scalar(a) for a in aliases) + "]\n")
        else:
            out.append("    aliases: []\n")
        if r["summary"]:
            out.append(f'    summary: {content_model._dump_scalar(r["summary"])}\n')
        if r["first_seen"]:
            out.append(f'    first_seen: {r["first_seen"]}\n')
        if r["merged_into"]:
            out.append(f'    merged_into: "{r["merged_into"]}"\n')
        if r["relations"]:
            out.append("    relations:\n")
            for rel in r["relations"]:
                out.append(f'      - to: "{rel.get("to", "")}"\n')
                out.append(f'        type: {rel.get("type", "related-to")}\n')
                if rel.get("source"):
                    out.append(f'        source: "{rel["source"]}"\n')
                if rel.get("note"):
                    out.append(f'        note: {content_model._dump_scalar(str(rel["note"]))}\n')
    out.append(BLOCK_END)
    return "".join(out)


def splice(raw: str, block: str) -> str:
    """Replace (or append) the tool-owned product block."""
    start = raw.find(BLOCK_START)
    if start != -1:
        end = raw.find(BLOCK_END, start)
        if end == -1:
            raise SystemExit("registry.yaml: PRODUCTS block start without its end marker")
        return raw[:start] + block + raw[end + len(BLOCK_END):]
    if not raw.endswith("\n"):
        raw += "\n"
    return raw + block


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="report drift and exit 1 without writing")
    ap.add_argument("--report", action="store_true",
                    help="print how every affected_products[] string resolved")
    args = ap.parse_args()

    entries = content_model.collect_entries()
    registry = content_model.load_registry()
    records, resolved = build_records(entries, registry)

    raw = REGISTRY_PATH.read_text()
    updated = splice(raw, render_block(records))

    if args.report:
        by_key: dict[str, list[str]] = defaultdict(list)
        for s, k in sorted(resolved.items()):
            by_key[k or "(vendor-only, not an entity)"].append(s)
        for k in sorted(by_key):
            spellings = by_key[k]
            marker = " *" if len(spellings) > 1 else ""
            print(f"{k}{marker}")
            for s in spellings:
                print(f"    {s}")

    n_new = len(records) - len(_existing_products(registry))
    dropped = sorted(s for s, k in resolved.items() if not k)
    summary = (f"{len(records)} product entities ({n_new} new) from "
               f"{len(resolved)} affected_products[] spellings across "
               f"{sum(1 for e in entries if e.get('affected_products'))} entries")

    if args.check:
        if updated != raw:
            print(f"DRIFT · {summary}", file=sys.stderr)
            print("run: python3 tools/sync_products.py", file=sys.stderr)
            return 1
        print(f"ok · {summary}")
        return 0

    if updated != raw:
        REGISTRY_PATH.write_text(updated)
        print(f"wrote {REGISTRY_PATH.relative_to(ROOT)} · {summary}")
    else:
        print(f"unchanged · {summary}")
    if dropped:
        print(f"not entities (vendor-only strings): {', '.join(dropped)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
